- name: Guardar as alterações no GitHub
        run: |
          git config --global user.name "Robo Radar"
          git config --global user.email "robo@radar360.com"
          git add dados.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automacao: Atualizacao Diaria de Radares" && git push)
